CREATE TABLE MEMBERS (
	MEMBER_ID SERIAL PRIMARY KEY, 
	FIRST_NAME VARCHAR(35) NOT NULL, 
	LAST_NAME VARCHAR(35) NOT NULL, 
	EMAIL VARCHAR(55) NOT NULL UNIQUE, 
	PHONE VARCHAR(15) NOT NULL,
	BIRTH_DATE DATE NOT NULL, 
	SEX VARCHAR(6),
	HEIGHT INTEGER,
	WEIGHT INTEGER,
	SIGN_UP_DATE DATE NOT NULL DEFAULT CURRENT_DATE
);
	
CREATE TABLE TRAINERS (
	TRAINER_ID SERIAL PRIMARY KEY, 
	FIRST_NAME VARCHAR(35) NOT NULL, 
	LAST_NAME VARCHAR(35) NOT NULL, 
	EMAIL VARCHAR(55) NOT NULL UNIQUE, 
	BIRTH_DATE DATE NOT NULL, 
	SEX VARCHAR(6),
	HIRE_DATE DATE NOT NULL, 
	PHONE VARCHAR(15) NOT NULL, 
	BIO TEXT
);
CREATE TABLE STAFF (
	STAFF_ID SERIAL PRIMARY KEY, 
	FIRST_NAME VARCHAR(35) NOT NULL, 
	LAST_NAME VARCHAR(35) NOT NULL, 
	EMAIL VARCHAR(55) NOT NULL UNIQUE, 
	BIRTH_DATE DATE NOT NULL, 
	SEX VARCHAR(6),
	HIRE_DATE DATE NOT NULL,
	SALARY INTEGER 
);

CREATE TABLE WORKOUTS(
	WORKOUT_ID SERIAL PRIMARY KEY, 
	WORKOUT_NAME VARCHAR(30) NOT NULL, 
	DURATION INT NOT NULL
);

CREATE TABLE ROOMS(
	ROOM_ID SERIAL PRIMARY KEY
	ROOM_NAME VARCHAR(15), 
	CAPACITY INT NOT NULL
);

CREATE TABLE CLASSES(
	CLASS_ID SERIAL PRIMARY KEY, 
	CLASS_NAME VARCHAR(55) NOT NULL,
	CLASS_TYPE VARCHAR(25),
	TRAINER_ID SERIAL REFERENCES TRAINERs ON DELETE SET NULL
);

CREATE TABLE EXERCISES(
	EXERCISE_ID SERIAL PRIMARY KEY, 
	EXERCISE_NAME VARCHAR(100) NOT NULL, 
	REPS INT, 
	SETS INT, 
	WORKOUT_ID INTEGER, 
	FOREIGN KEY (WORKOUT_ID) REFERENCES WORKOUTS(WORKOUT_ID) ON DELETE SET NULL
);

CREATE TABLE BOOKINGS(
	BOOKING_ID SERIAL PRIMARY KEY,
	CLASS_ID serial REFERENCES CLASSES ON DELETE CASCADE,
	DAY_OF_WEEK VARCHAR(15) NOT NULL, 
	TIME_OF_DAY TIME NOT NULL, 
	ROOM_ID INTEGER REFERENCES ROOMS ON DELETE SET NULL,
	DURATION INTEGER NOT NULL,
	UNIQUE (ROOM_ID, DAY_OF_WEEK, TIME_OF_DAY)
);


CREATE TABLE EQUIPMENT(
	EQUIPMENT_ID SERIAL PRIMARY KEY,
	EQUIPMENT_NAME VARCHAR(55), 
	ROOM_ID INTEGER, 
	QUANTITY INT, 
	PURCHASE_DATE DATE, 
	FOREIGN KEY (ROOM_ID) REFERENCES ROOMS ON DELETE SET NULL
)

CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID SERIAL PRIMARY KEY, 
	TRANSACTION_DATE DATE DEFAULT CURRENT_DATE,
	AMOUNT MONEY NOT NULL, 
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE SET NULL, 
	TRANSACTION_TYPE VARCHAR(255) NOT NULL
);


CREATE TABLE GOAL_TYPE(
    GOAL_TYPE_ID SERIAL PRIMARY KEY,
    GOAL_TITLE VARCHAR(50) NOT NULL, 
    TARGET_METRIC VARCHAR(50)
);

CREATE TABLE FITNESS_GOALS (
    GOAL_ID SERIAL PRIMARY KEY,
    MEMBER_ID INT REFERENCES MEMBERS ON DELETE CASCADE, 
    GOAL_NAME VARCHAR(100) NOT NULL,
    GOAL_DESCRIPTION TEXT,
    GOAL_TYPE_ID INT REFERENCES GOAL_TYPE ON DELETE SET NULL,
    TARGET_VALUE DECIMAL, 
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    ACHIEVED BOOLEAN DEFAULT FALSE
);


CREATE TABLE CLASS_HISTORY(
	 CLASS_HISTORY_ID SERIAL PRIMARY KEY,
	 TRAINER_ID SERIAL REFERENCES TRAINERS ON DELETE SET NULL, 
	 CLASS_ID SERIAL REFERENCES CLASSES,
	 NOTES TEXT NOT NULL,
	 ATTENDANCE INT
);

CREATE TABLE WORKOUT_HISTORY(
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE CASCADE, 
	WORKOUT_DATE DATE DEFAULT CURRENT_DATE, 
	WORKOUT_ID SERIAL REFERENCES WORKOUTS
);


CREATE TABLE MEMBER_CLASSES(
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE CASCADE, 
	CLASS_ID SERIAL REFERENCES CLASSES ON DELETE CASCADE,
	PRIMARY KEY (MEMBER_ID, CLASS_ID)
);
						   
						   








