CREATE TABLE MEMBERS (
	MEMBER_ID SERIAL PRIMARY KEY, 
	FIRST_NAME VARCHAR(35) NOT NULL, 
	LAST_NAME VARCHAR(35) NOT NULL, 
	EMAIL VARCHAR(55) NOT NULL UNIQUE, 
	PHONE VARCHAR(15) NOT NULL,
	BIRTH_DATE DATE NOT NULL, 
	SEX VARCHAR(6),
	HEIGHT INTEGER,
	WEIGHT INTEGER,
	SIGN_UP_DATE DATE NOT NULL DEFAULT CURRENT_DATE
);
	
CREATE TABLE TRAINERS (
	TRAINER_ID SERIAL PRIMARY KEY, 
	FIRST_NAME VARCHAR(35) NOT NULL, 
	LAST_NAME VARCHAR(35) NOT NULL, 
	EMAIL VARCHAR(55) NOT NULL UNIQUE, 
	BIRTH_DATE DATE NOT NULL, 
	SEX VARCHAR(6),
	HIRE_DATE DATE NOT NULL, 
	PHONE VARCHAR(15) NOT NULL, 
	BIO TEXT
);
CREATE TABLE STAFF (
	STAFF_ID SERIAL PRIMARY KEY, 
	FIRST_NAME VARCHAR(35) NOT NULL, 
	LAST_NAME VARCHAR(35) NOT NULL, 
	EMAIL VARCHAR(55) NOT NULL UNIQUE, 
	BIRTH_DATE DATE NOT NULL, 
	SEX VARCHAR(6),
	HIRE_DATE DATE NOT NULL,
	SALARY INTEGER 
);

CREATE TABLE WORKOUTS(
	WORKOUT_ID SERIAL PRIMARY KEY, 
	WORKOUT_NAME VARCHAR(30) NOT NULL, 
	DURATION INT NOT NULL
);

CREATE TABLE ROOMS(
	ROOM_NAME VARCHAR(15) PRIMARY KEY, 
	CAPACITY INT NOT NULL
);

CREATE TABLE CLASSES(
	CLASS_ID SERIAL PRIMARY KEY, 
	CLASS_NAME VARCHAR(55) NOT NULL,
	CLASS_TYPE VARCHAR(25),
	TRAINER_ID SERIAL REFERENCES TRAINERs ON DELETE SET NULL
);

CREATE TABLE EXERCISES(
	EXERCISE_ID SERIAL PRIMARY KEY, 
	EXERCISE_NAME VARCHAR(100) NOT NULL, 
	REPS INT, 
	SETS INT, 
	WORKOUT_ID INTEGER, 
	FOREIGN KEY (WORKOUT_ID) REFERENCES WORKOUTS(WORKOUT_ID) ON DELETE SET NULL
);

CREATE TABLE BOOKINGS(
	CLASS_ID serial REFERENCES CLASSES ON DELETE CASCADE,
	DAY_OF_WEEK VARCHAR(15) NOT NULL, 
	TIME_OF_DAY TIME NOT NULL, 
	ROOM_NAME VARCHAR(15) REFERENCES ROOMS ON DELETE SET NULL,
	DURATION INTEGER NOT NULL,
	PRIMARY KEY (CLASS_ID),
	UNIQUE (DAY_OF_WEEK, TIME_OF_DAY)
);


CREATE TABLE EQUIPMENT(
	EQUIPMENT_ID SERIAL PRIMARY KEY,
	EQUIPMENT_NAME VARCHAR(55), 
	ROOM_ID INTEGER, 
	QUANTITY INT, 
	PURCHASE_DATE DATE, 
	FOREIGN KEY (ROOM_ID) REFERENCES ROOMS ON DELETE SET NULL
)

CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID SERIAL PRIMARY KEY, 
	TRANSACTION_DATE DATE DEFAULT CURRENT_DATE,
	AMOUNT MONEY NOT NULL, 
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE SET NULL, 
	TRANSACTION_TYPE VARCHAR(255) NOT NULL
);


CREATE TABLE FITNESS_GOALS(
	GOAL_ID SERIAL PRIMARY KEY, 
	GOAL_TYPE VARCHAR(255), 
	UNIT VARCHAR(15)
);

CREATE TABLE MEMBER_GOALS (
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE CASCADE, 
	GOAL_ID SERIAL REFERENCES FITNESS_GOALS ON DELETE SET NULL, 
	AMOUNT INT NOT NULL, 
	DUE_DATE DATE, 
	PRIMARY KEY (MEMBER_ID, GOAL_ID)
);


CREATE TABLE TRAINING_SESSIONS_HISTORY(
	 TRAINER_ID SERIAL REFERENCES TRAINERS ON DELETE SET NULL, 
	 CLASS_ID SERIAL REFERENCES CLASSES,
	 NOTES TEXT NOT NULL,
	 ATTENDANCE INT
);

CREATE TABLE WORKOUT_HISTORY(
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE CASCADE, 
	WORKOUT_DATE DATE DEFAULT CURRENT_DATE, 
	WORKOUT_ID SERIAL REFERENCES WORKOUTS
);


CREATE TABLE MEMBER_CLASSES(
	MEMBER_ID SERIAL REFERENCES MEMBERS ON DELETE CASCADE, 
	CLASS_ID SERIAL REFERENCES CLASSES ON DELETE CASCADE,
	PRIMARY KEY (MEMBER_ID, CLASS_ID)
);
						   
						   








